import { useState, useEffect } from 'react';
import jsPDF from 'jspdf';
import { MarkdownRenderer } from './MarkdownRenderer';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  compiledText: string;
  subjectTags: string[];
}

export const CompiledNotesModal = ({ isOpen, onClose, compiledText, subjectTags }: Props) => {
  const [editableContent, setEditableContent] = useState(compiledText);
  const [viewMode, setViewMode] = useState<'edit' | 'preview'>('preview');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  // Sync editableContent when compiledText changes
  useEffect(() => {
    setEditableContent(compiledText);
  }, [compiledText]);

  if (!isOpen) return null;

  const today = new Date().toLocaleDateString('en-PK', {
    year: 'numeric', month: 'long', day: 'numeric'
  });

  const fileName = `BifrostAI_Notes_${subjectTags[0] || 'Study'}_${new Date().toISOString().split('T')[0]}.pdf`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(editableContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const stripMarkdown = (text: string): string => {
    return text
      .replace(/^#{1,6}\s+/gm, '')
      .replace(/\*\*\*(.+?)\*\*\*/g, '$1')
      .replace(/\*\*(.+?)\*\*/g, '$1')
      .replace(/\*(.+?)\*/g, '$1')
      .replace(/__(.+?)__/g, '$1')
      .replace(/_(.+?)_/g, '$1')
      .replace(/^\s*[\*\-\+]\s+/gm, '• ')
      .replace(/^\s*\d+\.\s+/gm, '')
      .replace(/^[-*_]{3,}$/gm, '─────────────────')
      .replace(/```[\s\S]*?```/g, '')
      .replace(/`(.+?)`/g, '$1')
      .replace(/^\s*>\s+/gm, '')
      .replace(/\[(.+?)\]\(.+?\)/g, '$1')
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  };

  const handleDownloadPDF = async () => {
    setIsGenerating(true);
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;
      let yPosition = 20;

      // Header background
      pdf.setFillColor(30, 58, 95);
      pdf.rect(0, 0, pageWidth, 35, 'F');

      // Header text
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Bifrost AI — Study Notes', margin, 15);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`${today}${subjectTags.length > 0 ? ' • ' + subjectTags.join(', ') : ''}`, margin, 25);

      yPosition = 50;

      // Content
      pdf.setTextColor(30, 30, 30);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'normal');

      // Split content into lines that fit the page width
      const cleanContent = stripMarkdown(editableContent);
      const lines = pdf.splitTextToSize(cleanContent, contentWidth);

      lines.forEach((line: string) => {
        if (yPosition > 270) {
          pdf.addPage();
          yPosition = 20;
        }
        const trimmed = line.trim();
        if (trimmed.length > 0 && trimmed.length < 60 && !trimmed.startsWith('•')) {
          pdf.setFont('helvetica', 'bold');
          pdf.setFontSize(12);
        } else {
          pdf.setFont('helvetica', 'normal');
          pdf.setFontSize(11);
        }
        pdf.text(line, margin, yPosition);
        yPosition += trimmed === '' ? 4 : 7;
      });

      // Footer
      pdf.setFontSize(9);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Bifrost AI • bifrostai.up.railway.app', margin, 285);

      pdf.save(fileName);
    } catch (err) {
      console.error('PDF generation failed:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">
      <div className="bg-gray-900 rounded-2xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl border border-gray-700">

        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-700">
          <div>
            <h2 className="text-xl font-bold text-white">📄 Compiled Study Notes</h2>
            <p className="text-sm text-gray-400 mt-1">
              Generated by Bifrost AI • {today}
              {subjectTags.length > 0 && ` • ${subjectTags.join(', ')}`}
            </p>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-white text-2xl leading-none cursor-pointer">✕</button>
        </div>

        {/* View Mode Toggle */}
        <div className="flex items-center gap-2 px-6 pt-4 pb-2 border-b border-gray-800 bg-gray-900/60">
          <button
            type="button"
            onClick={() => setViewMode('preview')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer ${
              viewMode === 'preview'
                ? 'bg-blue-600 text-white shadow-sm'
                : 'bg-gray-800 text-gray-400 hover:text-white hover:bg-gray-700'
            }`}
          >
            <span>👁 Preview</span>
          </button>
          <button
            type="button"
            onClick={() => setViewMode('edit')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer ${
              viewMode === 'edit'
                ? 'bg-blue-600 text-white shadow-sm'
                : 'bg-gray-800 text-gray-400 hover:text-white hover:bg-gray-700'
            }`}
          >
            <span>✏️ Edit</span>
          </button>
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-6 min-h-[380px]">
          {viewMode === 'preview' ? (
            <div className="bg-gray-800/60 border border-gray-700/60 rounded-xl p-5 min-h-[380px] text-gray-200 text-sm leading-relaxed overflow-y-auto">
              <MarkdownRenderer content={editableContent} className="text-gray-200 font-sans" />
            </div>
          ) : (
            <textarea
              className="w-full h-full min-h-[380px] bg-gray-800 text-gray-100 rounded-xl p-4 text-sm leading-relaxed resize-none border border-gray-600 focus:border-blue-500 focus:outline-none font-mono"
              value={editableContent}
              onChange={(e) => setEditableContent(e.target.value)}
              placeholder="Your compiled notes will appear here..."
            />
          )}
        </div>

        {/* Action Buttons */}
        <div className="flex gap-3 p-6 border-t border-gray-700">
          <button
            onClick={handleCopy}
            className="flex-1 py-3 rounded-xl border border-gray-600 text-gray-300 hover:text-white hover:border-gray-400 transition-colors font-medium cursor-pointer"
          >
            {copied ? '✓ Copied!' : '📋 Copy Text'}
          </button>
          <button
            onClick={handleDownloadPDF}
            disabled={isGenerating}
            className="flex-1 py-3 rounded-xl bg-blue-600 hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium transition-colors cursor-pointer"
          >
            {isGenerating ? '⏳ Generating PDF...' : '⬇️ Download as PDF'}
          </button>
        </div>
      </div>
    </div>
  );
};
